-- MySQL Script generated by MySQL Workbench
-- Thu Feb 14 15:42:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oper` DEFAULT CHARACTER SET utf8 ;
USE `oper` ;

-- -----------------------------------------------------
-- Table `oper`.`change_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`change_email` (
  `idchange_email` INT(11) NOT NULL AUTO_INCREMENT,
  `old_email` VARCHAR(191) NOT NULL,
  `new_email` VARCHAR(191) NOT NULL,
  `token` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idchange_email`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oper`.`enterprise_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`enterprise_type` (
  `identerprise_type` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`identerprise_type`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`vendor` (
  `idvendor` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `office_phone_number` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `office_address` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `pic_name` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `pic_mobile_number` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idvendor`),
  UNIQUE INDEX `vendor_email_unique` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`client_enterprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`client_enterprise` (
  `identerprise` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `enterprise_type_identerprise_type` INT(11) NOT NULL,
  `email` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `office_phone` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `office_address` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `pic_name` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `pic_phone` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `is_private` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `vendor_idvendor` INT(11) NOT NULL,
  `site_url` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `pic_email` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`identerprise`),
  UNIQUE INDEX `client_enterprise_email_unique` (`email` ASC),
  INDEX `fk_client_enterprise_enterprise_type1_idx` (`enterprise_type_identerprise_type` ASC),
  INDEX `fk_client_enterprise_vendor1_idx` (`vendor_idvendor` ASC),
  CONSTRAINT `fk_client_enterprise_enterprise_type1`
    FOREIGN KEY (`enterprise_type_identerprise_type`)
    REFERENCES `oper`.`enterprise_type` (`identerprise_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_enterprise_vendor1`
    FOREIGN KEY (`vendor_idvendor`)
    REFERENCES `oper`.`vendor` (`idvendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`drivertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`drivertype` (
  `iddrivertype` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL COMMENT '0 : PKWT\n1 : PKWT BACKTUP\n2 : FREELANCE\n',
  `descriptuon` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`iddrivertype`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`role` (
  `idrole` INT(11) NOT NULL AUTO_INCREMENT,
  `rolename` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `roletype` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`idrole`),
  UNIQUE INDEX `rolename_UNIQUE` (`rolename` ASC),
  UNIQUE INDEX `roletype_UNIQUE` (`roletype` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email_verified_at` DATETIME NULL DEFAULT NULL,
  `password` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `phonenumber` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `idrole` INT(11) NOT NULL,
  `vendor_idvendor` INT(11) NULL DEFAULT NULL,
  `client_enterprise_identerprise` INT(11) NULL DEFAULT NULL,
  `is_first_login` TINYINT(1) NULL DEFAULT '1',
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  INDEX `fk_user_role1` (`idrole` ASC),
  INDEX `fk_role_vendor1_idx` (`vendor_idvendor` ASC),
  INDEX `fk_role_client_enterprise1_idx` (`client_enterprise_identerprise` ASC),
  CONSTRAINT `fk_role_client_enterprise1`
    FOREIGN KEY (`client_enterprise_identerprise`)
    REFERENCES `oper`.`client_enterprise` (`identerprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_vendor1`
    FOREIGN KEY (`vendor_idvendor`)
    REFERENCES `oper`.`vendor` (`idvendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`idrole`)
    REFERENCES `oper`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`driver` (
  `iddriver` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(10) UNSIGNED NOT NULL,
  `birthdate` DATE NOT NULL,
  `address` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `drivertype_iddrivertype` INT(11) NOT NULL,
  `dispatcher_vendor_idvendor` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `insurance_policy_number` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `is_on_order` TINYINT(1) NOT NULL DEFAULT '0',
  `address` VARCHAR(191) NULL,
  PRIMARY KEY (`iddriver`),
  INDEX `fk_driver_users1_idx` (`users_id` ASC),
  INDEX `fk_driver_drivertype1_idx` (`drivertype_iddrivertype` ASC),
  INDEX `fk_driver_dispatcher1_idx` (`dispatcher_vendor_idvendor` ASC),
  CONSTRAINT `fk_driver_drivertype1`
    FOREIGN KEY (`drivertype_iddrivertype`)
    REFERENCES `oper`.`drivertype` (`iddrivertype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_driver_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `oper`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`inspector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`inspector` (
  `idinspector` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `phonenumber` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `client_enterprise_identerprise` INT(11) NOT NULL,
  PRIMARY KEY (`idinspector`),
  UNIQUE INDEX `phonenumber_UNIQUE` (`phonenumber` ASC),
  INDEX `fk_inspector_client_enterprise1_idx` (`client_enterprise_identerprise` ASC),
  CONSTRAINT `fk_inspector_client_enterprise1`
    FOREIGN KEY (`client_enterprise_identerprise`)
    REFERENCES `oper`.`client_enterprise` (`identerprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oper`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `queue` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `payload` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `attempts` TINYINT(3) UNSIGNED NOT NULL,
  `reserved_at` INT(10) UNSIGNED NULL DEFAULT NULL,
  `available_at` INT(10) UNSIGNED NOT NULL,
  `created_at` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `jobs_queue_index` (`queue` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 125
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`oauth_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`oauth_access_tokens` (
  `id` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `client_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `scopes` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_access_tokens_user_id_index` (`user_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`oauth_auth_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`oauth_auth_codes` (
  `id` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_id` INT(11) NOT NULL,
  `client_id` INT(10) UNSIGNED NOT NULL,
  `scopes` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`oauth_clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`oauth_clients` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `secret` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `redirect` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `personal_access_client` TINYINT(1) NOT NULL,
  `password_client` TINYINT(1) NOT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_clients_user_id_index` (`user_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`oauth_personal_access_clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`oauth_personal_access_clients` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` INT(10) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_personal_access_clients_client_id_index` (`client_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`oauth_refresh_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`oauth_refresh_tokens` (
  `id` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `access_token_id` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `revoked` TINYINT(1) NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `oauth_refresh_tokens_access_token_id_index` (`access_token_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`order_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`order_type` (
  `idorder_type` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idorder_type`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`task_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`task_template` (
  `task_template_id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_template_name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `client_enterprise_identerprise` INT(11) NULL DEFAULT NULL,
  `task_template_description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`task_template_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`order` (
  `idorder` INT(11) NOT NULL AUTO_INCREMENT,
  `task_template_task_template_id` INT(11) NOT NULL,
  `client_userid` INT(10) UNSIGNED NOT NULL,
  `driver_userid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `dispatcher_userid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `order_status` TINYINT(1) NOT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `booking_time` DATETIME NULL DEFAULT NULL,
  `origin_latitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `origin_longitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `destination_latitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `destination_longitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `client_vehicle_license` VARCHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `vehicle_brand` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `vehicle_type` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `vehicle_transmission` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `message` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `order_number` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `order_type_idorder_type` INT(11) NOT NULL,
  `vehicle_year` INT(11) NULL DEFAULT NULL,
  `vehicle_color` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `user_fullname` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `user_phonenumber` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `vehicle_owner` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `fk_order_task_template1_idx` (`task_template_task_template_id` ASC),
  INDEX `fk_order_users1_idx` (`client_userid` ASC),
  INDEX `fk_order_users2_idx` (`driver_userid` ASC),
  INDEX `fk_order_users3_idx` (`dispatcher_userid` ASC),
  INDEX `fk_order_order_type2_idx` (`order_type_idorder_type` ASC),
  CONSTRAINT `fk_order_order_type2`
    FOREIGN KEY (`order_type_idorder_type`)
    REFERENCES `oper`.`order_type` (`idorder_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_task_template1`
    FOREIGN KEY (`task_template_task_template_id`)
    REFERENCES `oper`.`task_template` (`task_template_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_users1`
    FOREIGN KEY (`client_userid`)
    REFERENCES `oper`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_users2`
    FOREIGN KEY (`driver_userid`)
    REFERENCES `oper`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_users3`
    FOREIGN KEY (`dispatcher_userid`)
    REFERENCES `oper`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`task` (
  `idtask` INT(11) NOT NULL AUTO_INCREMENT,
  `sequence` INT(11) NULL DEFAULT '0',
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `task_template_id` INT(11) NOT NULL,
  `is_required` TINYINT(1) NULL DEFAULT '1',
  `is_need_photo` TINYINT(1) NULL DEFAULT '0',
  `is_need_inspector_validation` TINYINT(1) NULL DEFAULT '0',
  `latitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`idtask`),
  INDEX `task_task_template_id_foreign` (`task_template_id` ASC),
  CONSTRAINT `task_task_template_id_foreign`
    FOREIGN KEY (`task_template_id`)
    REFERENCES `oper`.`task_template` (`task_template_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`order_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`order_tasks` (
  `idordertask` INT(11) NOT NULL AUTO_INCREMENT,
  `task_idtask` INT(11) NOT NULL,
  `order_idorder` INT(11) NOT NULL,
  `attachment_url` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `order_task_status` TINYINT(1) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `submit_latitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `submit_longitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `sequence` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `is_required` TINYINT(1) NULL,
  `is_need_photo` TINYINT(1) NULL,
  `is_need_inspector_validation` TINYINT(1) NULL,
  `latitude` VARCHAR(191) NULL,
  `longitude` VARCHAR(191) NULL,
  PRIMARY KEY (`idordertask`),
  INDEX `fk_order_tasks_task1_idx` (`task_idtask` ASC),
  INDEX `fk_order_tasks_order1_idx` (`order_idorder` ASC),
  INDEX `fk_order_tasks_inspector1_idx` (`sequence` ASC),
  CONSTRAINT `fk_order_tasks_inspector1`
    FOREIGN KEY (`sequence`)
    REFERENCES `oper`.`inspector` (`idinspector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_tasks_order1`
    FOREIGN KEY (`order_idorder`)
    REFERENCES `oper`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_tasks_task1`
    FOREIGN KEY (`task_idtask`)
    REFERENCES `oper`.`task` (`idtask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`password_resets` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`places` (
  `idplaces` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `address` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `latitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `longitude` DECIMAL(10,0) NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `identerprise` INT(11) NULL DEFAULT NULL,
  `places_type` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL,
  `places_type` INT NULL,
  PRIMARY KEY (`idplaces`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`request_otp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`request_otp` (
  `idrequest_otp` INT(11) NOT NULL AUTO_INCREMENT,
  `phonenumber` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `otp` VARCHAR(6) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `idordertask` INT(11) NOT NULL,
  PRIMARY KEY (`idrequest_otp`),
  INDEX `fk_request_otp_order_tasks1_idx` (`idordertask` ASC),
  CONSTRAINT `fk_request_otp_order_tasks1`
    FOREIGN KEY (`idordertask`)
    REFERENCES `oper`.`order_tasks` (`idordertask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`static_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`static_content` (
  `idstatic_content` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `content` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idstatic_content`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`web_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`web_menu` (
  `idmenu` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(191) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `parent_idmenu` INT(11) NULL DEFAULT NULL,
  `static_content_idstatic_content` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  `sequence` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idmenu`),
  INDEX `fk_menu_menu1_idx` (`parent_idmenu` ASC),
  INDEX `fk_web_menu_static_content1_idx` (`static_content_idstatic_content` ASC),
  CONSTRAINT `fk_menu_menu1`
    FOREIGN KEY (`parent_idmenu`)
    REFERENCES `oper`.`web_menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_web_menu_static_content1`
    FOREIGN KEY (`static_content_idstatic_content`)
    REFERENCES `oper`.`static_content` (`idstatic_content`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`role_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`role_access` (
  `role_access_id` INT(11) NOT NULL AUTO_INCREMENT,
  `idrole` INT(11) NOT NULL,
  `idmenu` INT(11) NOT NULL,
  PRIMARY KEY (`role_access_id`),
  INDEX `fk_role_has_menu_role1` (`idrole` ASC),
  INDEX `fk_role_has_menu_menu1_idx` (`idmenu` ASC),
  CONSTRAINT `fk_role_has_menu_menu1`
    FOREIGN KEY (`idmenu`)
    REFERENCES `oper`.`web_menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_menu_role1`
    FOREIGN KEY (`idrole`)
    REFERENCES `oper`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`vehicles` (
  `idvehicles` INT(11) NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `type` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `transmission` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `year` VARCHAR(5) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `color` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT(11) NULL DEFAULT NULL,
  `updated_by` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idvehicles`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `oper`.`client_site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`client_site` (
  `idclient_site` INT NOT NULL,
  `siteurl` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `client_enterprise_identerprise` INT(11) NOT NULL,
  PRIMARY KEY (`idclient_site`),
  INDEX `fk_client_site_client_enterprise1_idx` (`client_enterprise_identerprise` ASC),
  CONSTRAINT `fk_client_site_client_enterprise1`
    FOREIGN KEY (`client_enterprise_identerprise`)
    REFERENCES `oper`.`client_enterprise` (`identerprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oper`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oper`.`attendance` (
  `id` INT NOT NULL,
  `users_id` INT(10) UNSIGNED NOT NULL,
  `clock_in` DATETIME NULL,
  `clock_out` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `updated_by` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `image_url` VARCHAR(191) NULL,
  `remark` VARCHAR(191) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attendance_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_attendance_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `oper`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
